env:
  browser: true
  commonjs: true
  node: true
  es6: true
extends: 
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  comma-dangle:
    - error
    - only-multiline
  semi:
    - error
    - never
  no-unused-vars: 1
  react/react-in-jsx-scope: 0
  react/prop-types: 2
  no-dupe-keys: error
  no-constant-condition: error
  no-duplicate-case: error
  no-empty: error
  no-extra-boolean-cast: error
  no-irregular-whitespace: error
  no-unexpected-multiline: error
  no-unreachable: error
  array-callback-return: error
  complexity: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-empty-function: error
  no-empty-pattern: error
  no-redeclare: error
  no-useless-call: error
  no-useless-concat: error
  no-warning-comments: warn
  radix: error
  no-shadow: error
  no-undef: error
  no-unused-vars: error
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-exit: error
  no-sync: error
  block-spacing: error
  brace-style: error
  camelcase: error
  comma-spacing: error
  comma-style: error
  indent: 
    - error
    - 2
  max-depth:
    - error
    - 10
  newline-per-chained-call: error