env:
  browser: true
  commonjs: true
  node: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: 1
  indent: 2
  linebreak-style: 2
  quotes: 2
  semi: 2
  no-unused-vars: 1
  react/react-in-jsx-scope: 0
  react/prop-types: 2