env:
  browser: true
  commonjs: true
  node: true
  shared-node-browser: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: 1
  react/react-in-jsx-scope: 0
  react/prop-types: 
    - error
    - ignore:
      - dispatch