env:
  browser: true
  commonjs: true
  node: true
  es6: true
  jest: true
parser: babel-eslint
extends: stipsan
ecmaFeatures:
  modules: true
rules:
  no-console: off
  react/jsx-filename-extension: off
  import/imports-first: off
  import/no-extraneous-dependencies: off
