sudo: false
language: node_js
node_js:
- "6.4"
script: npm test -- --coverage
after_script: npm run coverage
notifications:
  email: false
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
    - CXX=g++-4.8
addons:
  code_climate:
      repo_token: be662185acd1fa423350262b2cc391da59e240f6b0e8afd3648295d03c11a272
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
